### ISSUE TITLE
haryu-example_issue

### ISSUE THREAD

**Issue by Paul2021-R** [webservVer2-0/webServ#1]
### 내용
무엇을 하려고 발행하는 Issue 인지 적어 주시면 됩니다! 

- - - 
### TODO List
- [ ] example 1 : 간단 설명(옵션)
- [ ] example 2 : 간단 설명(옵션)
- [ ] example 3 : 간단 설명(옵션)
- [ ] compile 되는 순간 make 되는지 판단하는 git Action 집어넣기

**Comment by Paul2021-R** [comment]
<img width="928" alt="스크린샷 2023-02-16 오후 11 12 51" src="https://user-images.githubusercontent.com/80471693/219388493-d03a8f62-5d2f-4964-b470-4f065828255d.png">

create a branch 를 누르면 현재 기본 branch 를 기준으로 작성이 됩니다!
