### ISSUE TITLE
jinypark_haryu-part-standard

### ISSUE THREAD

**Issue by Paul2021-R** [webservVer2-0/webServ#11]
작업 직전에 메인 브랜치 역할을 할 브랜치를 할당합니다. 해당 브랜치에서 작업해야할 내용들에 대한 hot branch 를 할당해서 진행하고, 합쳐 보면서 진척과 작업 진행 과정을 동기화합니다. (안정성 등등을 위해서..)
- - -
### TODO List
- [x] 캐싱 클래스 작성하기 : 최적의 반응속도 대응하기 위하여, conf.d 파일을 기반으로 index.html 과 같은 정적 데이터들에서 kevent 전에 작업을 진행하고, 최대한 정적 페이지 호출에서 kevent를 거치지 않고 최적화 될 수 있도록 개선 역할을 하는 장치 
  - default file cache 
  - error page cache 
  - 필요사항(?)
    - 메서드 담당자들이 보다 편하게 쓸 수 있도록 고려할 것 
- [ ] logger(kevent / structure) : 기본적으로 config 파일을 읽고, 해당 config의 접속 로그, 에러로그를 작성한다. 
  - config 세팅하는 과정에서 fd 활성화 -> server 별로 준비를 해야 하나(?) 
  - 그렇다면 파일 이름이 같으면 어떻게하지...?! 
  - append 모드로 로깅 진행 
  - access, error log를 구분하는 것은 접속 자체와 에러 케이스인 경우의 디버깅 용의 내용이 필요하기 때문에 이분할 하여 작업한다. 
  - error log의 경우, errno, strerrno(errno)를 활용하여서 디버깅을 넣어주고, 협의하에 custom 메시지를 입력 가능하도록 만든다. 
- [x] error checking(kevent / structure) : 에러를 체킹해주며, 에러 발견 시 kevent 를 통한 작업 처리 전에 모든 처리를 마무리 하고, 중간에 작업을 처리해야 하는 것들을 모두 스킵하고 error html 페이지를 덮어씌워주고, 작업의 진행 로직을 바꿔버린다(정상 요청 페이지에서 에러페이지를 전달해주는 방식으로)
  - kevent 회귀 직전에 함수형으로 구성된 function으로 error status 점검 
  - error page cache에서 page 를 strdup을 통해 복사 전달
  - event filter 를 client fd 에 대해 EV_WRITE 로 설정하여 kevent에서 정상적으로 method 파트를 스킵할 수 있도록 한다.
