### ISSUE TITLE
jinypark-POST 요청시 발생하는 버그

### ISSUE THREAD

**Issue by learnershigh** [webservVer2-0/webServ#110]
## Description

POST요청을 처리하면서 생기는 버그들을 정리해봤습니다.

## Progress

- [x] post_method.cpp / WorkFilePost()
1. client 안 멤버 변수 msg_length를 초기화하지 않아 처음에 쓰레기값이 들어갑니다.
2. 함수 내부 변수, 멤버 변수 간 자료형이 달라 생기는 계산 오차(int와 size_t)
3. `if (total_write_len > entity_len) {` 분기로 진입했을때 FD의 처리와 ERR_FIN을 사용하는 곳이 없어 이벤트 루프를 돌 때 오류가 생깁니다.
- [x] delete_page.cpp / MakeDeleteBody()
1. `if (IsDirectory(ent)) {
        continue;` 무한 루프 발생
- [x] post_method.cpp / MakeFilePath()
1. 로직 오류로 인한 파일 이름 생성 실패 ex) `(1)./storage/temp/var/image.png`
- [x] #112
1. `entity_len = std::stol(len);` 자료형이 달라 문제가 생길 수 있음.

## ETC
ResetConnection 후 filter->GetType() 에서 프로그램이 터지는 경우가 있는데 정확한 이유는 모르겠고 터지기전의 이벤트의 FD를 확인해보니 File step의 FD 였습니다. (정확하지 않음)

**Comment by khk811** [comment]
3월 24일 (금) 스크럼 후 제가 #110 이슈 처리를 담당하게 되었습니다.
post_method.cpp에서 말씀해주신 에러 내역을 수정하겠습니다.
(RequestHandler.cpp / EntityParse()는 sangtale님이 수정해주셨습니다. #112 이슈는 제가 todo를 잘못 눌러서 생겨버렸습니다;; 죄송합니다.)

### TODO
**WorkFilePost()**
- [ ] write_length 변수 타입을 ssize_t로 수정
- [ ] write_lenght가 -1인지를 먼저 판단하는 로직을 추가
##### total_len > entity_len 일때, 
- [ ] open()한 fd close() 처리
- [ ] open directory 파일을 unlink()
- [ ] file write 이벤트를 삭제

**MakeFilePath()**
- [ ] 파일 이름 생성 수정 : .find('.') 대신 rfind('.')로 수정

추가적으로 POST후 delete page가 뜨지 않는 오류가 있다고 해서 해당 사항도 수정할 예정입니다.
- [ ] POST후 delete page가 나오게 수정

**Comment by khk811** [comment]
1. write_result를 int에서 ssize_t로 변경하고, 그에 맞게 코드를 수정하였습니다.
2. total_len > entity_len 인 경우의 코드를 삭제하였습니다.
3. MakeFilePath() : 중복파일에 숫자가 붙는 위치를 수정하였습니다.
1과 3을 처리하니 delete page가 자동으로 잘 나오더군요.
